// src/data/medicineData.js

export const medicineData = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    drugCode: "PARA500",
    pharmacyName: "Civil Hospital Pharmacy",
    quantity: 0,
    status: "Out of Stock",
    lastUpdated: "2025-09-24 09:00",
  },
  {
    id: 2,
    name: "Amoxicillin 250mg",
    drugCode: "AMOX250",
    pharmacyName: "Royal Pharmacy",
    quantity: 0,
    status: "Out of Stock",
    lastUpdated: "2025-09-24 08:30",
  },
  {
    id: 3,
    name: "Metformin 500mg",
    drugCode: "MET500",
    pharmacyName: "Jivan Medical Store",
    quantity: 25,
    status: "Low Stock",
    lastUpdated: "2025-09-23 17:00",
  },
  {
    id: 4,
    name: "Aspirin 75mg",
    drugCode: "ASP75",
    pharmacyName: "Aggarwal Medicos",
    quantity: 5000,
    status: "In Stock",
    lastUpdated: "2025-09-24 07:45",
  },
  {
    id: 5,
    name: "Atorvastatin 20mg",
    drugCode: "ATORV20",
    pharmacyName: "Civil Hospital Pharmacy",
    quantity: 45,
    status: "Low Stock",
    lastUpdated: "2025-09-24 09:15",
  },
  {
    id: 6,
    name: "Insulin Glargine",
    drugCode: "INSG100",
    pharmacyName: "Gupta Pharma",
    quantity: 0,
    status: "Out of Stock",
    lastUpdated: "2025-09-23 20:00",
  },
  {
    id: 7,
    name: "Cetirizine 10mg",
    drugCode: "CET10",
    pharmacyName: "Royal Pharmacy",
    quantity: 1200,
    status: "In Stock",
    lastUpdated: "2025-09-22 14:00",
  },
  {
    id: 8,
    name: "Salbutamol Inhaler",
    drugCode: "SALB-INH",
    pharmacyName: "Dashmesh Medicos",
    quantity: 15,
    status: "Low Stock",
    lastUpdated: "2025-09-24 06:00",
  },
  {
    id: 9,
    name: "Omeprazole 20mg",
    drugCode: "OME20",
    pharmacyName: "Jivan Medical Store",
    quantity: 8000,
    status: "In Stock",
    lastUpdated: "2025-09-24 10:00",
  },
  {
    id: 10,
    name: "ORS Powder",
    drugCode: "ORS-P",
    pharmacyName: "Ahuja Pharmacy",
    quantity: 0,
    status: "Out of Stock",
    lastUpdated: "2025-09-24 09:45",
  },
  {
    id: 11,
    name: "Losartan 50mg",
    drugCode: "LOS50",
    pharmacyName: "Singla Health Care",
    quantity: 3200,
    status: "In Stock",
    lastUpdated: "2025-09-23 11:00",
  },
  {
    id: 12,
    name: "Albendazole 400mg",
    drugCode: "ALB400",
    pharmacyName: "Nabha Medical Hall",
    quantity: 2500,
    status: "In Stock",
    lastUpdated: "2025-09-21 18:00",
  },
  {
    id: 13,
    name: "Diclofenac Gel",
    drugCode: "DICL-GEL",
    pharmacyName: "Friends Medicos",
    quantity: 12,
    status: "Low Stock",
    lastUpdated: "2025-09-24 10:15",
  },
  {
    id: 14,
    name: "Gliclazide 80mg",
    drugCode: "GLIC80",
    pharmacyName: "Civil Hospital Pharmacy",
    quantity: 3300,
    status: "In Stock",
    lastUpdated: "2025-09-24 09:05",
  },
];
